steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/arch-server',
      '--target', 'production',
      '--cache-from', 'gcr.io/$PROJECT_ID/arch-server:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/arch-server']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'arch-server'
    - '--image'
    - 'gcr.io/$PROJECT_ID/arch-server'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--memory'
    - '4Gi'
    - '--set-env-vars'
    - 'USE_GCS=true,RUST_LOG=info,GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
    - '--service-account'
    - 'arch-server@$PROJECT_ID.iam.gserviceaccount.com'

images:
  - 'gcr.io/$PROJECT_ID/arch-server'

timeout: '1800s'  # 30 minutes
